"""
FPGA Realization Pipeline
==========================
Phase A: real Yosys synthesis. Phase B: real nextpnr-ice40 placement +
timing, chained off Yosys's iCE40-mapped JSON netlist — against a Verilog
module either chained from digital_logic's verilog_structural (see
shared/orchestrator.py's sequential-result threading) or generated by this
sub-domain's own dedicated LLM prompt when asked standalone with no
prebuilt input.

Phase B replaces Phase A's generic `synth` with `synth_ice40`, so
`cell_counts`/`total_cells`/`lut_count` now mean real iCE40 primitives
(SB_LUT4, etc.) and real placed-and-routed fabric usage (ICESTORM_LC),
not technology-independent generic cells.

Graceful degrade at TWO independent points (mirrors analog_sim/pipeline.py's
NgspiceRunError handling):
  - Yosys unavailable/fails -> LLM-estimated plan only, verified=False,
    synthesis_error set. No placement is attempted.
  - Yosys succeeds but nextpnr unavailable/fails -> the real cell_counts/
    total_cells/verified=True from Yosys are KEPT; only placement_error is
    set and lut_count/placement/timing_report stay unset. Losing placement
    doesn't erase synthesis data that's already real.
Never a hard failure for what should be a soft failure.

Stages (streaming): input_generation, execution, proof_of_work, final_result
"""
import json
from pathlib import Path
from typing import Dict, Any, Callable, Iterator, Optional

from .yosys_runner import run_yosys_synthesis, YosysRunError
from .nextpnr_runner import run_nextpnr_placement, NextpnrRunError
from .schematic import render_placement_schematic, PlacementSchematicError

RUNS_DIR = Path(__file__).parent.parent / "simforge_runs"
DEFAULT_PACKAGE = "hx8k-ct256"

_LLM_PROMPT = """You are an FPGA design expert. Given a user question, produce a JSON object
describing a synthesizable Verilog module for it.

Return JSON with these fields:
- "system_type": short name for the FPGA design
- "verilog_source": a complete, synthesizable Verilog module (behavioral or
  structural) implementing the design. Must be valid Verilog-2005 and
  define exactly one top-level module.
- "top_module": the exact name of the top-level module declared in verilog_source
- "assumptions": list of assumptions
- "plain_summary": one-sentence summary

Return ONLY the JSON, no other text.

User question: {question}"""


def _parse_llm_response(raw):
    from ..shared.llm_utils import parse_llm_json
    return parse_llm_json(raw)


def _build_model_parameters(plan):
    """
    Convert an FPGA plan into structured editable parameters for the
    Seemulator Formulated Model pane. The Verilog source is the editable
    field; rerun re-synthesizes against the edited source.
    """
    return [
        {
            "id": "verilog_source",
            "name": "Verilog Source",
            "value": plan.get("verilog_source", ""),
            "unit": "",
            "editable": True,
            "section": "COMPONENTS",
        },
        {
            "id": "top_module",
            "name": "Top Module",
            "value": plan.get("top_module", ""),
            "unit": "",
            "editable": False,
            "section": "COMPONENTS",
        },
    ]


def _to_standardized(result):
    has_placement = bool(result.get("placement"))
    return {
        "sub_domain": "fpga_realization",
        "tool_used": "nextpnr" if has_placement else "yosys",
        "domain": "Circuits",
        "system_type": result.get("system_type", "FPGA Design"),
        "solver_name": "yosys + nextpnr" if has_placement else "yosys",
        "status": result.get("status", "completed"),
        "netlist": result.get("verilog_source", "") or "",
        "raw_output_path": result.get("raw_output_path", ""),
        "metrics": result.get("metrics", []),
        "visualization_type": "diagram_only",
        "frequency_response": None,
        "time_series": None,
        "schematic_svg": result.get("schematic_svg", ""),
        "schematic_error": result.get("schematic_error"),
        "assumptions": result.get("assumptions", []),
        "unsupported_aspects": result.get("unsupported_aspects", []),
        "plain_summary": result.get("plain_summary"),
        "lut_count": result.get("lut_count", 0),
        "timing_report": result.get("timing_report"),
        "verilog_source": result.get("verilog_source"),
        "top_module": result.get("top_module"),
        "cell_counts": result.get("cell_counts"),
        "total_cells": result.get("total_cells"),
        "verified": result.get("verified", False),
        "proof_of_work": result.get("proof_of_work"),
        "synthesis_error": result.get("synthesis_error"),
        "placement": result.get("placement"),
        "placement_error": result.get("placement_error"),
    }


def _run_synthesis(plan: Dict[str, Any], result: Dict[str, Any], task_id: str) -> Optional[Dict[str, Any]]:
    """
    Mutates `result` in place: real Yosys ice40-mapped stats on success,
    graceful degrade (verified=False + synthesis_error explaining why) on
    YosysRunError. Never raises. Returns the raw yosys `stat` dict on
    success (so the caller can chain nextpnr off its json_netlist_path), or
    None on failure.
    """
    verilog_source = plan.get("verilog_source", "") or ""
    top_module = plan.get("top_module") or ""

    if not verilog_source.strip() or not top_module.strip():
        result["synthesis_error"] = "No Verilog source/top_module available to synthesize."
        result["verified"] = False
        result["proof_of_work"] = {"passed": False, "note": result["synthesis_error"]}
        return None

    try:
        stat = run_yosys_synthesis(
            verilog_source, top_module, target="ice40",
            runs_dir=RUNS_DIR, task_id=task_id,
        )
        result["cell_counts"] = stat["cell_counts"]
        result["total_cells"] = stat["total_cells"]
        result["raw_output_path"] = stat["log_path"]
        result["metrics"].append({"name": "Total Cells (iCE40-mapped)", "value": str(stat["total_cells"])})
        for cell_type, count in stat["cell_counts"].items():
            result["metrics"].append({"name": cell_type, "value": str(count)})
        result["verified"] = True
        result["proof_of_work"] = {
            "passed": True,
            "note": f"Real Yosys synthesis (synth_ice40): {stat['total_cells']} cell(s) "
                    f"in {stat['run_duration_s']}s ({stat['module_name']}).",
        }
        return stat
    except YosysRunError as exc:
        result["synthesis_error"] = str(exc)
        result["verified"] = False
        result["proof_of_work"] = {"passed": False, "note": f"Yosys synthesis unavailable: {exc}"}
        return None


def _run_placement(stat: Dict[str, Any], result: Dict[str, Any], task_id: str) -> None:
    """
    Mutates `result` in place with real nextpnr placement/timing on success.
    On NextpnrRunError, sets placement_error and leaves lut_count/placement/
    timing_report unset — deliberately does NOT touch verified/proof_of_work/
    cell_counts/total_cells, which already reflect Yosys's real (independent)
    success. Never raises.
    """
    json_netlist_path = stat.get("json_netlist_path")
    if not json_netlist_path:
        result["placement_error"] = "Yosys did not produce a JSON netlist for placement (unexpected)."
        return

    try:
        pnr = run_nextpnr_placement(
            json_netlist_path, package=DEFAULT_PACKAGE,
            runs_dir=RUNS_DIR, task_id=task_id,
        )
        result["lut_count"] = pnr["lut_count"]
        result["placement"] = pnr["placement"]
        result["timing_report"] = pnr["timing_report"]
        result["metrics"].append({"name": "LUTs Used (placed)", "value": str(pnr["lut_count"])})
        result["metrics"].append({"name": "Cells Placed", "value": str(len(pnr["placement"]))})
        result["proof_of_work"] = {
            "passed": True,
            "note": (f"Real Yosys+nextpnr: {pnr['lut_count']} LUT(s) placed & routed "
                     f"across {len(pnr['placement'])} cell(s) on iCE40 ({DEFAULT_PACKAGE})."),
        }
        try:
            result["schematic_svg"] = render_placement_schematic(pnr["placement"])
        except PlacementSchematicError:
            pass  # leave schematic_svg unset — generic fallback still applies
    except NextpnrRunError as exc:
        result["placement_error"] = str(exc)
        # Yosys's own success (verified=True, cell_counts, proof_of_work) is
        # left untouched — losing placement doesn't erase real synthesis data.


def _plain_summary_for(result: Dict[str, Any], plan: Dict[str, Any]) -> str:
    if result.get("synthesis_error"):
        fallback = (f"FPGA synthesis unavailable ({result['synthesis_error']}); "
                    f"showing an LLM-estimated design only — not verified by a real tool run.")
        return plan.get("plain_summary") or fallback
    base = (f"Real Yosys synthesis completed for {result.get('system_type', 'FPGA Design')}: "
            f"{result.get('total_cells', 0)} cell(s).")
    if result.get("placement"):
        base += f" Placed & routed on iCE40: {result.get('lut_count', 0)} LUT(s) used."
    elif result.get("placement_error"):
        base += f" Placement/timing unavailable ({result['placement_error']})."
    return base


def run_fpga_realization_pipeline(
    question: str,
    call_llm: Callable[[str], str],
    task_id: str,
    tool: str = "yosys",
    _prebuilt_input: dict = None,
) -> Dict[str, Any]:
    if _prebuilt_input:
        plan = _prebuilt_input
    else:
        prompt = _LLM_PROMPT.format(question=question)
        try:
            raw = call_llm(prompt)
            plan = _parse_llm_response(raw)
        except Exception as e:
            return _to_standardized({
                "status": "failed", "plain_summary": f"LLM call/parse failed: {e}",
            })

    result = {
        "system_type": plan.get("system_type", "FPGA Design"),
        "verilog_source": plan.get("verilog_source", ""),
        "top_module": plan.get("top_module", ""),
        "assumptions": plan.get("assumptions", []),
        "metrics": [],
        "status": "completed",
    }

    stat = _run_synthesis(plan, result, task_id)
    if stat is not None:
        _run_placement(stat, result, task_id)
    result["plain_summary"] = _plain_summary_for(result, plan)
    return _to_standardized(result)


def run_fpga_realization_pipeline_stream(
    question: str,
    call_llm: Callable[[str], str],
    task_id: str,
    tool: str = "yosys",
    _prebuilt_input: dict = None,
) -> Iterator[Dict[str, Any]]:
    yield {"stage": "input_generation", "status": "start"}
    if _prebuilt_input:
        plan = _prebuilt_input
        yield {"stage": "input_generation", "status": "done",
               "system_type": plan.get("system_type", "FPGA Design")}
    else:
        prompt = _LLM_PROMPT.format(question=question)
        try:
            raw = call_llm(prompt)
        except Exception as e:
            yield {"stage": "input_generation", "status": "failed", "error": str(e)}
            yield {"stage": "final_result", "result": _to_standardized({
                "status": "failed", "plain_summary": f"LLM call failed: {e}"})}
            return
        try:
            plan = _parse_llm_response(raw)
        except Exception as e:
            yield {"stage": "input_generation", "status": "failed", "error": str(e)}
            yield {"stage": "final_result", "result": _to_standardized({
                "status": "failed", "plain_summary": f"Parse error: {e}"})}
            return
        yield {"stage": "input_generation", "status": "done",
               "system_type": plan.get("system_type", "FPGA Design")}

    # Seemulator contract §2.3: emit model after input generation, before execution.
    yield {
        "event": "model",
        "data": {
            "input_file": json.dumps(plan, indent=2),
            "parameters": _build_model_parameters(plan),
        },
    }

    yield {"stage": "execution", "status": "start", "tool": "yosys"}

    result = {
        "system_type": plan.get("system_type", "FPGA Design"),
        "verilog_source": plan.get("verilog_source", ""),
        "top_module": plan.get("top_module", ""),
        "assumptions": plan.get("assumptions", []),
        "metrics": [],
        "status": "completed",
    }
    stat = _run_synthesis(plan, result, task_id)
    if stat is not None:
        yield {"stage": "execution", "status": "start", "tool": "nextpnr"}
        _run_placement(stat, result, task_id)
        yield {"stage": "execution", "status": "done", "tool": "nextpnr"}
    else:
        yield {"stage": "execution", "status": "done", "tool": "yosys"}

    ok = bool(result.get("verified"))
    detail = (result.get("proof_of_work") or {}).get("note", "")
    yield {"stage": "proof_of_work", "status": "done" if ok else "failed", "detail": detail}

    result["plain_summary"] = _plain_summary_for(result, plan)
    yield {"stage": "final_result", "result": _to_standardized(result)}
