/**
 * Circuits Domain Netlister
 * Generates SPICE netlists from circuit parameters
 */

/**
 * Generate SPICE netlist for RC Low-Pass Filter
 * @param {Object} params - Circuit parameters
 * @returns {string} - SPICE netlist
 */
function generateRCFilterNetlist(params) {
  const { R1 = 1000, C1 = 1e-6, vin = 5, frequency = 1000 } = params;
  
  return `* RC Low-Pass Filter
* Generated by SimForge
Vin 1 0 DC ${vin} AC 1
R1 1 2 ${R1}
C1 2 0 ${C1}
.AC DEC 10 ${frequency/10} ${frequency*10}
.TRAN 1u 10m
.PLOT AC V(2)
.PLOT TRAN V(2)
.END`;
}

/**
 * Generate SPICE netlist for Voltage Divider
 * @param {Object} params - Circuit parameters
 * @returns {string} - SPICE netlist
 */
function generateVoltageDividerNetlist(params) {
  const { R1 = 10000, R2 = 10000, vin = 12, load_resistance } = params;
  
  let netlist = `* Voltage Divider
* Generated by SimForge
Vin 1 0 DC ${vin}
R1 1 2 ${R1}
R2 2 0 ${R2}`;
  
  if (load_resistance) {
    netlist += `\nRload 2 0 ${load_resistance}`;
  }
  
  netlist += `\n.OP
.PLOT DC V(2)
.END`;
  
  return netlist;
}

/**
 * Generate SPICE netlist for Buck Converter
 * @param {Object} params - Circuit parameters
 * @returns {string} - SPICE netlist
 */
function generateBuckConverterNetlist(params) {
  const { vin = 12, vout = 5, L1 = 22e-6, C1 = 47e-6, frequency = 500000, load_resistance = 10 } = params;
  const duty_cycle = params.duty_cycle || (vout / vin);
  
  return `* Buck Converter
* Generated by SimForge
Vin 1 0 DC ${vin}
Vswitch 1 2 PULSE(0 ${vin} 0 1n 1n ${(1/frequency)*duty_cycle} ${1/frequency})
L1 2 3 ${L1}
C1 3 0 ${C1}
Rload 3 0 ${load_resistance}
D1 3 0 DIODE
.MODEL DIODE D
.TRAN 1n 100u
.PLOT TRAN V(3) I(L1)
.END`;
}

/**
 * Generate SPICE netlist for Common Emitter Amplifier
 * @param {Object} params - Circuit parameters
 * @returns {string} - SPICE netlist
 */
function generateCommonEmitterNetlist(params) {
  const { Rc = 4700, Re = 1000, Rb1 = 47000, Rb2 = 10000, Vcc = 12, beta = 100, frequency = 1000 } = params;
  
  return `* Common Emitter Amplifier
* Generated by SimForge
Vcc 4 0 DC ${Vcc}
Rc 4 3 ${Rc}
Re 5 0 ${Re}
Rb1 4 2 ${Rb1}
Rb2 2 0 ${Rb2}
Q1 3 2 5 NPN
.MODEL NPN NPN(BF=${beta})
Vin 1 0 AC 1m SIN(0 1m ${frequency})
Cin 1 2 1u
Cout 3 6 10u
Rload 6 0 10000
.AC DEC 10 ${frequency/10} ${frequency*10}
.TRAN 1u 1m
.PLOT AC V(6)
.PLOT TRAN V(6)
.END`;
}

/**
 * Generate SPICE netlist based on circuit type
 * @param {string} circuitType - Type of circuit
 * @param {Object} params - Circuit parameters
 * @returns {string} - SPICE netlist
 */
export function generateNetlist(circuitType, params) {
  const generators = {
    'RC Low-Pass Filter': generateRCFilterNetlist,
    'RC High-Pass Filter': generateRCFilterNetlist, // Reuse RC filter
    'Voltage Divider': generateVoltageDividerNetlist,
    'Buck Converter': generateBuckConverterNetlist,
    'Boost Converter': generateBuckConverterNetlist, // Similar structure
    'Common Emitter Amplifier': generateCommonEmitterNetlist,
    'Op-Amp Circuit': generateCommonEmitterNetlist, // Placeholder
    'LC Filter': generateRCFilterNetlist, // Placeholder
    'Rectifier': generateVoltageDividerNetlist, // Placeholder
    'Oscillator': generateRCFilterNetlist // Placeholder
  };
  
  const generator = generators[circuitType];
  if (!generator) {
    // Generic template for unknown circuit types
    return `* ${circuitType}
* Generated by SimForge
* Add your circuit components here
.END`;
  }
  
  return generator(params);
}

/**
 * Parse parameters from netlist (reverse operation)
 * @param {string} netlist - SPICE netlist
 * @returns {Object} - Extracted parameters
 */
export function parseNetlistParameters(netlist) {
  const params = {};
  
  // Parse resistors
  const resistorRegex = /R(\w+)\s+(\d+)\s+(\d+)\s+([\d.eE+-]+)/g;
  let match;
  while ((match = resistorRegex.exec(netlist)) !== null) {
    params[`R${match[1]}`] = parseFloat(match[4]);
  }
  
  // Parse capacitors
  const capacitorRegex = /C(\w+)\s+(\d+)\s+(\d+)\s+([\d.eE+-]+)/g;
  while ((match = capacitorRegex.exec(netlist)) !== null) {
    params[`C${match[1]}`] = parseFloat(match[4]);
  }
  
  // Parse inductors
  const inductorRegex = /L(\w+)\s+(\d+)\s+(\d+)\s+([\d.eE+-]+)/g;
  while ((match = inductorRegex.exec(netlist)) !== null) {
    params[`L${match[1]}`] = parseFloat(match[4]);
  }
  
  // Parse voltage sources
  const voltageRegex = /V(\w+)\s+(\d+)\s+(\d+)\s+DC\s+([\d.eE+-]+)/g;
  while ((match = voltageRegex.exec(netlist)) !== null) {
    params[`V${match[1]}`] = parseFloat(match[4]);
  }
  
  return params;
}
