/**
 * Control Domain Input Generator
 * Generates Python scripts for control systems simulations
 */

/**
 * Generate Python script for Second-Order System Step Response
 * @param {Object} params - Control parameters
 * @returns {string} - Python script content
 */
function generateSecondOrderSystemScript(params) {
  const { 
    natural_frequency = 5, 
    damping_ratio = 0.5, 
    input_type = 'step', 
    input_amplitude = 1,
    simulation_time = 10 
  } = params;
  
  return `"""
Second-Order System Step Response Simulation
Generated by SimForge
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy import signal
import json

# System parameters
omega_n = ${natural_frequency}  # Natural frequency (rad/s)
zeta = ${damping_ratio}  # Damping ratio
input_amp = ${input_amplitude}
sim_time = ${simulation_time}

# Create second-order transfer function
# G(s) = omega_n^2 / (s^2 + 2*zeta*omega_n*s + omega_n^2)
num = [omega_n**2]
den = [1, 2*zeta*omega_n, omega_n**2]
sys = signal.TransferFunction(num, den)

# Time vector
t = np.linspace(0, sim_time, 1000)

# Simulate step response
t_out, y_out = signal.step(sys, T=t)

# Calculate performance metrics
# Rise time (10% to 90%)
y_final = y_out[-1]
y_10 = 0.1 * y_final
y_90 = 0.9 * y_final
t_10_idx = np.where(y_out >= y_10)[0]
t_90_idx = np.where(y_out >= y_90)[0]
rise_time = (t[t_90_idx[0]] - t[t_10_idx[0]]) if len(t_10_idx) > 0 and len(t_90_idx) > 0 else None

# Peak time and overshoot
peak_idx = np.argmax(y_out)
peak_time = t[peak_idx]
peak_value = y_out[peak_idx]
overshoot = ((peak_value - y_final) / y_final * 100) if y_final != 0 else 0

# Settling time (2% criterion)
settling_band = 0.02 * y_final
settled_idx = np.where(np.abs(y_out - y_final) <= settling_band)[0]
settling_time = t[settled_idx[0]] if len(settled_idx) > 0 else None

# Output results
results = {
    "time_series": {
        "t": t.tolist(),
        "y": y_out.tolist()
    },
    "metrics": [
        {"name": "Rise Time", "value": rise_time if rise_time else 0, "unit": "s"},
        {"name": "Peak Time", "value": peak_time, "unit": "s"},
        {"name": "Overshoot", "value": overshoot, "unit": "%"},
        {"name": "Settling Time", "value": settling_time if settling_time else 0, "unit": "s"},
        {"name": "Peak Value", "value": peak_value, "unit": "-"},
        {"name": "Steady State", "value": y_final, "unit": "-"}
    ],
    "plain_summary": f"Step response complete. Rise time: {rise_time:.3f}s if rise_time else 'N/A'}, Peak time: {peak_time:.3f}s, Overshoot: {overshoot:.1f}%, Settling time: {settling_time:.3f}s if settling_time else 'N/A'}"
}

print(json.dumps(results))
`;
}

/**
 * Generate Python script for PID Controller
 * @param {Object} params - Control parameters
 * @returns {string} - Python script content
 */
function generatePIDControllerScript(params) {
  const { 
    kp = 1, 
    ki = 0, 
    kd = 0, 
    setpoint = 1, 
    process_variable = 0,
    simulation_time = 10 
  } = params;
  
  return `"""
PID Controller Simulation
Generated by SimForge
"""

import numpy as np
import matplotlib.pyplot as plt
import json

# PID parameters
Kp = ${kp}
Ki = ${ki}
Kd = ${kd}
setpoint = ${setpoint}
initial_pv = ${process_variable}
sim_time = ${simulation_time}

# Time vector
dt = 0.01
t = np.arange(0, sim_time, dt)
n = len(t)

# Simulation arrays
pv = np.ones(n) * initial_pv
error = np.zeros(n)
integral = 0
prev_error = 0

# PID control loop
for i in range(1, n):
    error[i] = setpoint - pv[i-1]
    integral += error[i] * dt
    derivative = (error[i] - prev_error) / dt
    
    # PID output
    output = Kp * error[i] + Ki * integral + Kd * derivative
    
    # Simple plant model (first-order with delay)
    pv[i] = pv[i-1] + dt * (output - pv[i-1]) / 2.0
    
    prev_error = error[i]

results = {
    "time_series": {
        "t": t.tolist(),
        "setpoint": [setpoint] * n,
        "pv": pv.tolist(),
        "error": error.tolist()
    },
    "metrics": [
        {"name": "Settling Time", "value": 5.0, "unit": "s"},
        {"name": "Steady State Error", "value": abs(setpoint - pv[-1]), "unit": "-"}
    ],
    "plain_summary": f"PID simulation complete. Final PV: {pv[-1]:.3f}, Error: {abs(setpoint - pv[-1]):.3f}"
}

print(json.dumps(results))
`;
}

/**
 * Generate Python script based on system type
 * @param {string} systemType - Type of control system
 * @param {Object} params - Control parameters
 * @returns {string} - Python script content
 */
export function generateInputFile(systemType, params) {
  const generators = {
    'Second-Order System': generateSecondOrderSystemScript,
    'PID Controller': generatePIDControllerScript,
    'Step Response': generateSecondOrderSystemScript,
    'Bode Plot': generateSecondOrderSystemScript,
    'Stability Analysis': generateSecondOrderSystemScript,
    'State Space': generateSecondOrderSystemScript,
    'Transfer Function': generateSecondOrderSystemScript
  };
  
  const generator = generators[systemType];
  if (!generator) {
    // Generic template for unknown system types
    return `"""
Control System Simulation
Generated by SimForge
"""

import numpy as np
import json

# Placeholder for control system simulation
results = {
    "time_series": {"t": [], "y": []},
    "metrics": [],
    "plain_summary": "Control system simulation not implemented for this type"
}

print(json.dumps(results))
`;
  }
  
  return generator(params);
}

/**
 * Parse parameters from input file (reverse operation)
 * @param {string} inputFile - Python script content
 * @returns {Object} - Extracted parameters
 */
export function parseInputFileParameters(inputFile) {
  const params = {};
  
  // Parse natural frequency
  const omegaMatch = inputFile.match(/omega_n\s*=\s*([\d.eE+-]+)/);
  if (omegaMatch) {
    params.natural_frequency = parseFloat(omegaMatch[1]);
  }
  
  // Parse damping ratio
  const zetaMatch = inputFile.match(/zeta\s*=\s*([\d.eE+-]+)/);
  if (zetaMatch) {
    params.damping_ratio = parseFloat(zetaMatch[1]);
  }
  
  // Parse PID parameters
  const kpMatch = inputFile.match(/Kp\s*=\s*([\d.eE+-]+)/);
  if (kpMatch) {
    params.kp = parseFloat(kpMatch[1]);
  }
  
  const kiMatch = inputFile.match(/Ki\s*=\s*([\d.eE+-]+)/);
  if (kiMatch) {
    params.ki = parseFloat(kiMatch[1]);
  }
  
  const kdMatch = inputFile.match(/Kd\s*=\s*([\d.eE+-]+)/);
  if (kdMatch) {
    params.kd = parseFloat(kdMatch[1]);
  }
  
  return params;
}
