/**
 * Aerospace Domain Input Generator
 * Generates XFOIL input files from aerospace parameters
 */

/**
 * Generate XFOIL input file for Airfoil Analysis
 * @param {Object} params - Aerospace parameters
 * @returns {string} - XFOIL input file content
 */
function generateAirfoilInput(params) {
  const { 
    airfoil = 'naca0012',
    reynolds = 1e6,
    mach = 0.0,
    aoa_min = -5,
    aoa_max = 15,
    aoa_step = 1,
    ncrit = 9
  } = params;
  
  return `! XFOIL Input File
! Generated by SimForge
! Airfoil Analysis

PLOP
G
FILL

NACA ${airfoil}
OPER
VISC ${reynolds}
MACH ${mach}
ITER 500
ASEQ ${aoa_min} ${aoa_max} ${aoa_step}
PACC
polar_${airfoil}.txt
dump_${airfoil}.txt
`;

}

/**
 * Generate XFOIL input file based on system type
 * @param {string} systemType - Type of aerospace system
 * @param {Object} params - Aerospace parameters
 * @returns {string} - XFOIL input file content
 */
export function generateInputFile(systemType, params) {
  const generators = {
    'Airfoil Analysis': generateAirfoilInput,
    'Nozzle Flow': generateAirfoilInput, // Placeholder - would use different solver
    'Propulsion': generateAirfoilInput, // Placeholder
    'Aerodynamics': generateAirfoilInput, // Placeholder
    'Orbital Mechanics': generateAirfoilInput // Placeholder
  };
  
  const generator = generators[systemType];
  if (!generator) {
    // Generic template for unknown system types
    return `! XFOIL Input File
! Generated by SimForge
`;
  }
  
  return generator(params);
}

/**
 * Parse parameters from input file (reverse operation)
 * @param {string} inputFile - XFOIL input file content
 * @returns {Object} - Extracted parameters
 */
export function parseInputFileParameters(inputFile) {
  const params = {};
  
  // Parse airfoil name
  const airfoilMatch = inputFile.match(/NACA\s+([\w\d]+)/);
  if (airfoilMatch) {
    params.airfoil = airfoilMatch[1];
  }
  
  // Parse Reynolds number
  const reynoldsMatch = inputFile.match(/VISC\s+([\d.eE+-]+)/);
  if (reynoldsMatch) {
    params.reynolds = parseFloat(reynoldsMatch[1]);
  }
  
  // Parse Mach number
  const machMatch = inputFile.match(/MACH\s+([\d.eE+-]+)/);
  if (machMatch) {
    params.mach = parseFloat(machMatch[1]);
  }
  
  // Parse angle of attack sequence
  const aseqMatch = inputFile.match(/ASEQ\s+([\d.eE+-]+)\s+([\d.eE+-]+)\s+([\d.eE+-]+)/);
  if (aseqMatch) {
    params.aoa_min = parseFloat(aseqMatch[1]);
    params.aoa_max = parseFloat(aseqMatch[2]);
    params.aoa_step = parseFloat(aseqMatch[3]);
  }
  
  return params;
}
