/**
 * Structural Domain Input Generator
 * Generates CalculiX input files from structural parameters
 */

/**
 * Generate CalculiX input file for Cantilever Beam
 * @param {Object} params - Structural parameters
 * @returns {string} - CalculiX .inp file content
 */
function generateCantileverBeamInput(params) {
  const { 
    length = 100, 
    width = 20, 
    height = 20, 
    wall_thickness = 2, 
    ribs = 0,
    load_magnitude = 100, 
    youngs_modulus = 200000, 
    poisson_ratio = 0.29,
    density = 7850 
  } = params;
  
  // Convert to meters for CalculiX
  const L = length / 1000;
  const W = width / 1000;
  const H = height / 1000;
  const WT = wall_thickness / 1000;
  
  return `*HEADING
Cantilever Beam Analysis
Generated by SimForge

*PREPRINT, HISTORY=MODEL, FREQUENCY=0

*NODE, NSET=Nall
1, 0.0, 0.0, 0.0
2, ${L}, 0.0, 0.0
3, ${L}, ${W}, 0.0
4, 0.0, ${W}, 0.0
5, 0.0, 0.0, ${H}
6, ${L}, 0.0, ${H}
7, ${L}, ${W}, ${H}
8, 0.0, ${W}, ${H}

*ELEMENT, TYPE=C3D8R, ELSET=Eall
1, 1, 2, 3, 4, 5, 6, 7, 8

*MATERIAL, NAME=Steel
*ELASTIC
${youngs_modulus}, ${poisson_ratio}
*DENSITY
${density}

*SOLID SECTION, MATERIAL=Steel, ELSET=Eall

*BOUNDARY
Nfix, 1, 3

*CLOAD
Nload, 3, -${load_magnitude}

*STEP
*STATIC
*OUTPUT, FIELD
*NODE FILE
*EL FILE
*END STEP`;
}

/**
 * Generate CalculiX input file for Simply Supported Beam
 * @param {Object} params - Structural parameters
 * @returns {string} - CalculiX .inp file content
 */
function generateSimplySupportedBeamInput(params) {
  const { 
    length = 1000, 
    width = 50, 
    height = 50, 
    load_magnitude = 1000, 
    youngs_modulus = 200000, 
    poisson_ratio = 0.29 
  } = params;
  
  const L = length / 1000;
  const W = width / 1000;
  const H = height / 1000;
  
  return `*HEADING
Simply Supported Beam Analysis
Generated by SimForge

*NODE, NSET=Nall
1, 0.0, 0.0, 0.0
2, ${L}, 0.0, 0.0
3, ${L}, ${W}, 0.0
4, 0.0, ${W}, 0.0
5, 0.0, 0.0, ${H}
6, ${L}, 0.0, ${H}
7, ${L}, ${W}, ${H}
8, 0.0, ${W}, ${H}

*ELEMENT, TYPE=C3D8R, ELSET=Eall
1, 1, 2, 3, 4, 5, 6, 7, 8

*MATERIAL, NAME=Steel
*ELASTIC
${youngs_modulus}, ${poisson_ratio}

*SOLID SECTION, MATERIAL=Steel, ELSET=Eall

*BOUNDARY
Nleft, 2, 2
Nright, 2, 2

*CLOAD
Ncenter, 3, -${load_magnitude}

*STEP
*STATIC
*OUTPUT, FIELD
*NODE FILE
*EL FILE
*END STEP`;
}

/**
 * Generate CalculiX input file based on system type
 * @param {string} systemType - Type of structural system
 * @param {Object} params - Structural parameters
 * @returns {string} - CalculiX .inp file content
 */
export function generateInputFile(systemType, params) {
  const generators = {
    'Cantilever Beam': generateCantileverBeamInput,
    'Simply Supported Beam': generateSimplySupportedBeamInput,
    'Fixed Beam': generateCantileverBeamInput, // Similar structure
    'Column Buckling': generateCantileverBeamInput, // Placeholder
    'Plate Bending': generateCantileverBeamInput, // Placeholder
    'Shell Analysis': generateCantileverBeamInput, // Placeholder
    'Truss Analysis': generateCantileverBeamInput, // Placeholder
    'Frame Analysis': generateCantileverBeamInput // Placeholder
  };
  
  const generator = generators[systemType];
  if (!generator) {
    // Generic template for unknown system types
    return `*HEADING
${systemType}
Generated by SimForge
*END STEP`;
  }
  
  return generator(params);
}

/**
 * Parse parameters from input file (reverse operation)
 * @param {string} inputFile - CalculiX .inp file content
 * @returns {Object} - Extracted parameters
 */
export function parseInputFileParameters(inputFile) {
  const params = {};
  
  // Parse Young's modulus
  const elasticMatch = inputFile.match(/\*ELASTIC\s+([\d.eE+-]+)\s*,\s*([\d.eE+-]+)/);
  if (elasticMatch) {
    params.youngs_modulus = parseFloat(elasticMatch[1]);
    params.poisson_ratio = parseFloat(elasticMatch[2]);
  }
  
  // Parse density
  const densityMatch = inputFile.match(/\*DENSITY\s+([\d.eE+-]+)/);
  if (densityMatch) {
    params.density = parseFloat(densityMatch[1]);
  }
  
  // Parse load
  const loadMatch = inputFile.match(/\*CLOAD\s+[\w]+\s+\d+\s+-([\d.eE+-]+)/);
  if (loadMatch) {
    params.load_magnitude = parseFloat(loadMatch[1]);
  }
  
  return params;
}
