"""
ngspice Runner (subprocess + wrdata)
======================================
Replaces .raw binary parsing entirely. We build a netlist whose .control
block uses ngspice's `wrdata` command to dump results as a plain
whitespace-delimited ASCII table, then read that table with a ~15-line
parser. This keeps ngspice as the actual solver (accurate, handles any
topology/nonlinearity/model the AI netlist throws at it) while removing the
"headache parsing raw output" problem you flagged.

Supports the three analysis types the AI's `analysis.type` field can
request: operating_point, transient, ac.
"""

import re
import shutil
import subprocess
import time
from pathlib import Path
from typing import Dict, Any, List

from .netlist_translate import lcapy_netlist_to_spice, NetlistTranslationError


class NgspiceRunError(Exception):
    pass


def _sanitize_node_for_vector(node: str) -> str:
    """ngspice vector names can't contain '/'; SPICE node names rarely do,
    but be defensive since node names come from AI-generated text."""
    return re.sub(r"[^A-Za-z0-9_]", "_", node)


def _inject_bjt_models(component_lines: List[str]) -> List[str]:
    """Ensure BJT lines (Q-prefix) have a model name and matching .model
    directive. Lcapy netlists omit model names, but ngspice requires them."""
    fixed = []
    needs_npn = False
    needs_pnp = False
    for line in component_lines:
        tokens = line.split()
        if tokens and tokens[0][0].upper() == "Q":
            if len(tokens) == 4:
                fixed.append(line + " NPNDEFAULT")
                needs_npn = True
            elif len(tokens) >= 5:
                model = tokens[4]
                if model.upper() in ("NPN", "NPNDEFAULT"):
                    needs_npn = True
                elif model.upper() in ("PNP", "PNPDEFAULT"):
                    needs_pnp = True
                fixed.append(line)
            else:
                fixed.append(line)
        else:
            fixed.append(line)
    if needs_npn:
        fixed.append(".model NPNDEFAULT NPN(Is=10f Bf=100 Vaf=75 Cjc=10p Cje=15p)")
    if needs_pnp:
        fixed.append(".model PNPDEFAULT PNP(Is=10f Bf=100 Vaf=75 Cjc=10p Cje=15p)")
    return fixed


def _inject_diode_models(component_lines: List[str]) -> List[str]:
    fixed = []
    needed = {}
    for line in component_lines:
        t = line.split()
        if t and t[0][0].upper() == "D" and len(t) >= 4:
            m = t[3]
            if not m.replace(".", "").replace("-", "").isdigit():
                needed[m] = 1
        fixed.append(line)
    for m in needed:
        if "zener" in m.lower() or "dzen" in m.lower():
            fixed.append(f".model {m} D(Bv=5.1 Ibv=20m)")
        else:
            fixed.append(f".model {m} D(Is=10f N=1)")
    return fixed


def _build_deck(system_type: str, component_lines: List[str], analysis: Dict[str, Any],
                 probe_nodes: List[str]) -> str:
    """Assemble the full .cir deck: title, components, analysis command,
    and a .control block that writes a clean ASCII table via wrdata."""
    analysis_type = (analysis or {}).get("type", "operating_point")
    args = (analysis or {}).get("args", {}) or {}

    probes = [f"v({node})" for node in probe_nodes] if probe_nodes else []

    component_lines = _inject_bjt_models(component_lines)
    component_lines = _inject_diode_models(component_lines)
    lines = [f"* {system_type}", "* Generated by Seemulator (AI netlist -> SPICE)"]
    lines.extend(component_lines)

    lines.append(".control")
    lines.append("set filetype=ascii")

    if analysis_type == "operating_point":
        lines.append("op")
        # For op-point there's no sweep scale, so print instead of wrdata.
        for node in probe_nodes:
            lines.append(f"print v({node})")
        lines.append("write simforge_out.raw")  # harmless if unused by parser

    elif analysis_type == "transient":
        step = args.get("step", "1u")
        stop = args.get("stop", "1m")
        start = args.get("start", "0")
        lines.append(f"tran {step} {stop} {start}")
        if probes:
            lines.append("set wr_singlescale")
            lines.append("set wr_vecnames")
            lines.append("wrdata simforge_out.txt " + " ".join(probes))

    elif analysis_type == "ac":
        variation = args.get("variation", "dec")
        points = args.get("points_per_decade", args.get("points", 20))
        start_freq = args.get("start_freq", "1")
        stop_freq = args.get("stop_freq", "1Meg")
        lines.append(f"ac {variation} {points} {start_freq} {stop_freq}")
        if probes:
            lines.append("set wr_singlescale")
            lines.append("set wr_vecnames")
            # vdb()/vp() give magnitude(dB) and phase(deg) directly, which
            # is exactly what a Bode plot needs, so no ratio math client-side.
            db_probes = [f"vdb({node})" for node in probe_nodes]
            phase_probes = [f"vp({node})" for node in probe_nodes]
            lines.append("wrdata simforge_out.txt " + " ".join(db_probes + phase_probes))

    else:
        raise NgspiceRunError(f"Unsupported analysis type: {analysis_type}")

    lines.append("quit")
    lines.append(".endc")
    lines.append(".end")
    return "\n".join(lines) + "\n"


def _parse_wrdata_table(path: Path, probe_nodes: List[str], analysis_type: str) -> Dict[str, Any]:
    """
    wrdata with `set wr_singlescale` + `set wr_vecnames` writes:
        <scale_name> <vec1_name> <vec2_name> ...
        <scale_val>  <v1_val>    <v2_val>    ...
        ...
    One shared scale column, then one column per requested vector — exactly
    the shape we want, no per-node duplicate-scale columns to strip.
    """
    if not path.exists():
        raise NgspiceRunError(f"Expected ngspice output file not found: {path}")

    with open(path, "r") as f:
        raw_lines = [ln.strip() for ln in f if ln.strip()]

    if len(raw_lines) < 2:
        raise NgspiceRunError(f"ngspice output file '{path.name}' has no data rows.")

    header = raw_lines[0].split()
    data_rows = [ln.split() for ln in raw_lines[1:]]
    ncols = len(header)
    data_rows = [row for row in data_rows if len(row) == ncols]

    columns: Dict[str, List[float]] = {name: [] for name in header}
    for row in data_rows:
        for name, val in zip(header, row):
            try:
                columns[name].append(float(val))
            except ValueError:
                columns[name].append(float("nan"))

    scale_name = header[0]
    scale = columns[scale_name]

    result: Dict[str, Any] = {"scale_name": scale_name, "scale": scale}

    if analysis_type == "ac":
        # header columns are vdb(node)/vp(node) pairs for each probe
        db_series, phase_series = {}, {}
        for node in probe_nodes:
            db_key = next((h for h in header if h.lower() == f"vdb({node})".lower()), None)
            ph_key = next((h for h in header if h.lower() == f"vp({node})".lower()), None)
            if db_key:
                db_series[node] = columns[db_key]
            if ph_key:
                phase_series[node] = columns[ph_key]
        result["magnitude_db"] = db_series
        result["phase_deg"] = phase_series
    else:
        series = {}
        for node in probe_nodes:
            key = next((h for h in header if h.lower() == f"v({node})".lower()), None)
            if key:
                series[node] = columns[key]
        result["voltage"] = series

    return result


def _ensure_ac_magnitude(component_lines: List[str], analysis_type: str) -> List[str]:
    """
    Generic, topology-agnostic fix: for AC analysis, any independent
    voltage/current source (V*/I*) needs an explicit AC magnitude or its
    AC amplitude defaults to zero. That silently breaks the whole sweep —
    e.g. vdb() of a zero signal makes ngspice raise "argument out of range
    for db" internally (while still exiting 0), which starves any
    downstream wrdata call of output. This appends "AC 1" to every V/I
    source line that doesn't already declare one, regardless of circuit
    topology.
    """
    if analysis_type != "ac":
        return component_lines

    fixed = []
    for line in component_lines:
        tokens = line.split()
        if tokens and tokens[0][0].upper() in ("V", "I") and not re.search(r"\bAC\b", line, re.IGNORECASE):
            fixed.append(line + " AC 1")
        else:
            fixed.append(line)
    return fixed


def _extract_ngspice_errors(log_text: str) -> List[str]:
    """ngspice frequently exits 0 even after an internal error aborts the
    rest of the .control block (e.g. a bad db()/log() argument, a missing
    node, a convergence failure printed as 'Error: ...'). Scan the log
    text directly instead of trusting the process return code."""
    return [ln.strip() for ln in log_text.splitlines() if ln.strip().lower().startswith("error")]


def _parse_op_point_stdout(stdout: str, probe_nodes: List[str]) -> Dict[str, Any]:
    """operating_point uses `print v(node)` -> parse from stdout since a
    single scalar doesn't warrant a wrdata table."""
    voltages: Dict[str, float] = {}
    for node in probe_nodes:
        pattern = re.compile(rf"v\({re.escape(node)}\)\s*=\s*([\-0-9.eE+]+)", re.IGNORECASE)
        match = pattern.search(stdout)
        if match:
            voltages[node] = float(match.group(1))
    return {"scale_name": None, "scale": [], "voltage": {n: [v] for n, v in voltages.items()}}


def run_ngspice(
    task_id: str,
    system_type: str,
    unified_netlist: str,
    analysis: Dict[str, Any],
    probe_nodes: List[str],
    runs_dir: Path,
    timeout_seconds: int = 120,
) -> Dict[str, Any]:
    """
    Full flow: AI netlist -> deterministic SPICE translation -> ngspice
    subprocess -> wrdata ASCII parse -> standardized result dict.
    """
    print(f"[FLOW TRACE] 6/9 ngspice_runner.py — run_ngspice() called for task_id={task_id}, analysis={analysis.get('type', 'operating_point')}")
    try:
        component_lines = lcapy_netlist_to_spice(unified_netlist)
    except NetlistTranslationError as exc:
        raise NgspiceRunError(f"Netlist translation failed: {exc}")

    analysis_type = (analysis or {}).get("type", "operating_point")
    component_lines = _ensure_ac_magnitude(component_lines, analysis_type)
    deck_text = _build_deck(system_type, component_lines, analysis, probe_nodes)

    work_dir = runs_dir / task_id
    work_dir.mkdir(parents=True, exist_ok=True)
    deck_path = work_dir / "circuit.cir"
    deck_path.write_text(deck_text)

    if shutil.which("ngspice") is None:
        raise NgspiceRunError("ngspice binary not found on PATH.")

    log_path = work_dir / "ngspice.log"
    cmd = ["ngspice", "-b", "-o", log_path.name, str(deck_path)]
    start = time.time()
    try:
        result = subprocess.run(
            cmd, capture_output=True, text=True, timeout=timeout_seconds, cwd=work_dir
        )
    except subprocess.TimeoutExpired:
        raise NgspiceRunError(f"ngspice timed out after {timeout_seconds}s.")
    elapsed = time.time() - start

    output_txt = work_dir / "simforge_out.txt"
    log_text = log_path.read_text() if log_path.exists() else ""
    ngspice_errors = _extract_ngspice_errors(log_text)

    # ngspice frequently exits 0 even when an internal error aborted the
    # rest of the .control block (confirmed: a bad vdb() argument does
    # exactly this). Check the log content, not just returncode, before
    # trusting that a missing output file means something vaguer.
    if ngspice_errors:
        raise NgspiceRunError(
            f"ngspice reported an internal error (exit code {result.returncode}): "
            f"{'; '.join(ngspice_errors)}\nFull log:\n{log_text[-1500:]}"
        )

    if result.returncode != 0 and not output_txt.exists() and not log_path.exists():
        raise NgspiceRunError(
            f"ngspice failed (exit {result.returncode}).\nstderr: {result.stderr}\nstdout: {result.stdout}"
        )

    if analysis_type == "operating_point":
        parsed = _parse_op_point_stdout(log_text, probe_nodes)
        if not parsed["voltage"]:
            raise NgspiceRunError(
                f"Could not find probe node voltages in ngspice output. "
                f"stderr: {result.stderr}\nlog: {log_text[-800:]}"
            )
    else:
        if not output_txt.exists():
            raise NgspiceRunError(
                f"ngspice completed (exit {result.returncode}) but produced no wrdata output file. "
                f"This usually means the .control block aborted before reaching wrdata. "
                f"Full log:\n{log_text[-1500:]}"
            )
        parsed = _parse_wrdata_table(output_txt, probe_nodes, analysis_type)

    parsed["analysis_type"] = analysis_type
    parsed["run_duration_s"] = round(elapsed, 3)
    parsed["deck_path"] = str(deck_path)
    # operating_point has no wrdata table (values come from stdout), so fall
    # back to the deck path as the closest thing to a "raw output" on disk.
    parsed["output_path"] = str(output_txt) if output_txt.exists() else str(deck_path)
    parsed["ngspice_returncode"] = result.returncode
    return parsed
