"""
CalculiX Solver
Structural FEA solver running in Docker container
"""

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from typing import Dict, Any
import subprocess
import shutil
from pathlib import Path
import json
import time

def run_calculix_docker(task_id: str, input_file: Dict[str, Any], options: Dict[str, Any]) -> Dict[str, Any]:
    """
    Run CalculiX solver in Docker container
    
    Args:
        task_id: Task UUID
        input_file: {filename, content} - complete CalculiX input deck
        options: Additional options
    """
    
    # Extract input deck content from input_file
    inp_content = input_file.get("content", "")
    filename = input_file.get("filename", "beam.inp")
    
    # Create working directory (use project directory for better Docker volume support on macOS)
    base_dir = Path(__file__).parent.parent.parent / "simforge_runs"
    base_dir.mkdir(parents=True, exist_ok=True)
    work_dir = base_dir / task_id
    work_dir.mkdir(parents=True, exist_ok=True)
    
    # Step 1: Write input deck to file (already generated by AI)
    inp_path = work_dir / filename
    
    with open(inp_path, 'w') as f:
        f.write(inp_content)
    
    # Step 2: Run Docker container
    # Note: Old mesh generation and duplicate AI input generation removed - they referenced undefined variables
    # and duplicated the AI-generated input file already written in Step 1
    print(f"[CalculiX] Running solver for task {task_id}")
    
    try:
        # Check if Docker is available
        docker_available = shutil.which("docker") is not None
        
        if docker_available:
            # Run in Docker
            cmd = [
                "docker", "run", "--rm",
                "-v", f"{work_dir}:/work",
                "-w", "/work",
                "--cpus", "2",
                "--memory", "4g",
                "simforge-calculix:latest",
                "ccx", inp_path.stem
            ]
            
            start_time = time.time()
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=600)
            elapsed = time.time() - start_time
            
            print(f"[CalculiX] Solver stdout: {result.stdout[:500]}")
            print(f"[CalculiX] Solver stderr: {result.stderr[:500]}")
            print(f"[CalculiX] Return code: {result.returncode}")
            
            # List files in work directory after solver run
            print(f"[CalculiX] Files in work directory: {list(work_dir.glob('*'))}")
            
            if result.returncode != 0:
                print(f"[CalculiX] Solver failed: {result.stderr}")
                raise Exception(f"CalculiX solver failed: {result.stderr}")
                
        else:
            # Fallback: run locally if ccx is installed
            ccx_available = shutil.which("ccx") is not None
            
            if ccx_available:
                cmd = ["ccx", str(inp_path.stem)]
                start_time = time.time()
                result = subprocess.run(cmd, capture_output=True, text=True, cwd=work_dir, timeout=600)
                elapsed = time.time() - start_time
                
                if result.returncode != 0:
                    raise Exception(f"CalculiX solver failed: {result.stderr}")
            else:
                # No solver available - return synthetic result
                print("[CalculiX] No solver available, returning synthetic result")
                return generate_synthetic_result(task_id, input_file, options)
    
    except subprocess.TimeoutExpired:
        raise Exception("CalculiX solver timed out after 600 seconds")
    
    # Step 4: Parse output
    frd_path = work_dir / f"{inp_path.stem}.frd"
    
    if frd_path.exists():
        from parsers.frd_parser import parse_frd
        parsed = parse_frd(str(frd_path))
    else:
        # Fallback to synthetic result
        return generate_synthetic_result(task_id, input_file, options)
    
    # Step 5: Format result
    system_type = input_file.get("metadata", {}).get("system_type", "Beam")
    max_stress = parsed.get('metrics', [{}])[0].get('value', 0)
    try:
        max_stress_float = float(max_stress) if max_stress else 0.0
    except (ValueError, TypeError):
        max_stress_float = 0.0
    
    return {
        "domain": "Structural",
        "system_type": system_type,
        "solver_name": "CalculiX",
        "solver_version": "2.21",
        "metrics": parsed.get("metrics", []),
        "contour_field": parsed.get("contour_field", {}),
        "visualization_type": "contour_field",
        "plain_summary": f"FEA analysis complete. Max Von Mises stress: {max_stress_float:.1f} MPa",
        "raw_files": {
            "frd": str(frd_path) if frd_path.exists() else None,
            "inp": str(inp_path) if inp_path.exists() else None
        }
    }

def generate_calculix_input(inp_path: Path, length: float, width: float, height: float,
                           wall_thickness: float, ribs: int, load_magnitude: float,
                           youngs_modulus: float, poissons_ratio: float, density: float):
    """Generate CalculiX .inp file with proper mesh"""
    
    # Generate a simpler mesh with fewer elements for stability
    nx = 10  # Number of elements along length
    ny = 2   # Number of elements along width
    nz = 2   # Number of elements along height
    
    # Generate nodes
    nodes = []
    node_id = 1
    for i in range(nx + 1):
        for j in range(ny + 1):
            for k in range(nz + 1):
                x = i * length / nx
                y = j * width / ny
                z = k * height / nz
                nodes.append(f"{node_id}, {x:.6f}, {y:.6f}, {z:.6f}")
                node_id += 1
    
    # Generate elements (hexahedral)
    elements = []
    elem_id = 1
    for i in range(nx):
        for j in range(ny):
            for k in range(nz):
                # Calculate node indices for this element
                n1 = i * (ny + 1) * (nz + 1) + j * (nz + 1) + k + 1
                n2 = (i + 1) * (ny + 1) * (nz + 1) + j * (nz + 1) + k + 1
                n3 = (i + 1) * (ny + 1) * (nz + 1) + (j + 1) * (nz + 1) + k + 1
                n4 = i * (ny + 1) * (nz + 1) + (j + 1) * (nz + 1) + k + 1
                n5 = i * (ny + 1) * (nz + 1) + j * (nz + 1) + (k + 1) + 1
                n6 = (i + 1) * (ny + 1) * (nz + 1) + j * (nz + 1) + (k + 1) + 1
                n7 = (i + 1) * (ny + 1) * (nz + 1) + (j + 1) * (nz + 1) + (k + 1) + 1
                n8 = i * (ny + 1) * (nz + 1) + (j + 1) * (nz + 1) + (k + 1) + 1
                elements.append(f"{elem_id}, {n1}, {n2}, {n3}, {n4}, {n5}, {n6}, {n7}, {n8}")
                elem_id += 1
    
    # Find nodes at x=0 for boundary condition (cantilever - fix all DOF)
    fixed_nodes = [str(i * (ny + 1) * (nz + 1) + j * (nz + 1) + k + 1) for i in range(nx + 1) for j in range(ny + 1) for k in range(nz + 1) if i == 0]
    
    # Find nodes at x=length for load application (apply force in z-direction)
    load_nodes = [str(i * (ny + 1) * (nz + 1) + j * (nz + 1) + k + 1) 
                  for i in range(nx + 1) for j in range(ny + 1) for k in range(nz + 1) if i == nx]
    
    inp_content = f"""** CalculiX Input File - Generated by SimForge
** Beam: {length}mm span, {width}x{height}mm, {wall_thickness}mm wall
** Load: {load_magnitude}N
** Ribs: {ribs}
** Mesh: {len(nodes)} nodes, {len(elements)} elements

*HEADING
Beam Analysis with {ribs} Internal Ribs
Static Linear Analysis

** ====================================================
** MATERIAL PROPERTIES
** ====================================================
*MATERIAL, NAME=STEEL
*ELASTIC
{youngs_modulus * 1000}, {poissons_ratio}
*DENSITY
{density}
*EXPANSION
1.2e-5

** ====================================================
** NODES
** ====================================================
*NODE, NSET=ALL
{chr(10).join(nodes)}

** ====================================================
** ELEMENTS
** ====================================================
*ELEMENT, TYPE=C3D8R, ELSET=BEAM
{chr(10).join(elements)}

** ====================================================
** MATERIAL ASSIGNMENT
** ====================================================
*SOLID SECTION, ELSET=BEAM, MATERIAL=STEEL

** ====================================================
** BOUNDARY CONDITIONS
** ====================================================
*BOUNDARY
{chr(10).join(f'{n}, 1, 3, 0.0' for n in fixed_nodes)}

** ====================================================
** OUTPUT
** ====================================================
*STEP
StaticAnalysis
*STATIC
1.0, 1.0, 1e-5, 1.0
*CLOAD
{chr(10).join(f'{n}, 3, {-load_magnitude / len(load_nodes):.2f}' for n in load_nodes)}
*NODE FILE
U, RF
*EL FILE
S, E, MISES
*END STEP
"""
    
    with open(inp_path, 'w') as f:
        f.write(inp_content)

def generate_simple_mesh(work_dir: Path, length: float, width: float, height: float,
                        wall_thickness: float, ribs: int) -> Path:
    """Generate simple mesh without Gmsh (fallback)"""
    # This is a placeholder - in production, Gmsh would be used
    mesh_path = work_dir / "mesh.msh"
    with open(mesh_path, 'w') as f:
        f.write("$MeshFormat\n2.2 0 8\n$EndMeshFormat\n")
    return mesh_path

def generate_synthetic_result(task_id: str, input_file: Dict[str, Any], options: Dict[str, Any]) -> Dict[str, Any]:
    """Generate synthetic FEA result (fallback when solver unavailable)
    
    Note: Uses placeholder defaults since model parameters are not available in this fallback path.
    """
    # Placeholder defaults for synthetic result
    length = 100.0  # mm, default fallback
    width = 20.0  # mm, default fallback
    height = 20.0  # mm, default fallback
    wall_thickness = 2.0  # mm, default fallback
    ribs = 0  # default fallback
    load_magnitude = 100.0  # N, default fallback
    youngs_modulus = 200.0  # GPa, steel default
    
    # Simple beam theory for synthetic result
    I = (width * height**3 - (width - 2*wall_thickness) * (height - 2*wall_thickness)**3) / 12
    max_stress = (load_magnitude * length / 2) * (height / 2) / I
    max_deflection = (load_magnitude * length**3) / (48 * youngs_modulus * 1000 * I)
    
    # Generate synthetic contour field
    n_points = 100
    x = [i * length / (n_points - 1) for i in range(n_points)]
    y = [0] * n_points
    z = [height / 2] * n_points
    stress = [max_stress * (1 - xi / length) for xi in x]
    
    return {
        "domain": "Structural",
        "system_type": "Beam",
        "solver_name": "CalculiX",
        "solver_version": "2.21",
        "metrics": [
            {"name": "Max Von Mises Stress", "value": f"{max_stress/1e6:.1f}", "unit": "MPa"},
            {"name": "Max Deflection", "value": f"{max_deflection:.2f}", "unit": "mm"},
            {"name": "Safety Factor", "value": f"{250/max_stress*1e6:.2f}", "unit": ""},
            {"name": "Note", "value": "Synthetic result - solver unavailable", "unit": ""}
        ],
        "contour_field": {
            "x": x,
            "y": y,
            "z": z,
            "stress": stress,
            "displacement": [max_deflection * (xi / length)**2 for xi in x]
        },
        "visualization_type": "contour_field",
        "plain_summary": f"Synthetic FEA result (solver unavailable). Max stress: {max_stress/1e6:.1f} MPa"
    }
