"""
Elmer Solver
Multi-physics solver running in Docker container
"""

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from typing import Dict, Any
import subprocess
import shutil
from pathlib import Path
import time

def run_elmer_docker(task_id: str, input_file: Dict[str, Any], options: Dict[str, Any]) -> Dict[str, Any]:
    """
    Run Elmer solver in Docker container
    
    Args:
        task_id: Task UUID
        input_file: {filename, content} - complete Elmer .sif file
        options: Additional options
    """
    
    # Extract sif content from input_file
    sif_content = input_file.get("content", "")
    filename = input_file.get("filename", "case.sif")
    
    # Create working directory (use project directory for better Docker volume support on macOS)
    base_dir = Path(__file__).parent.parent.parent / "simforge_runs"
    base_dir.mkdir(parents=True, exist_ok=True)
    work_dir = base_dir / task_id
    work_dir.mkdir(parents=True, exist_ok=True)
    
    # Step 1: Write .sif file to file (already generated by AI)
    sif_path = work_dir / filename
    
    with open(sif_path, 'w') as f:
        f.write(sif_content)
    
    # Step 2: Run Docker container
    print(f"[Elmer] Running solver for task {task_id}")
    
    try:
        # Check if Docker is available
        docker_available = shutil.which("docker") is not None
        
        if docker_available:
            # Run in Docker
            cmd = [
                "docker", "run", "--rm",
                "-v", f"{work_dir}:/work",
                "-w", "/work",
                "--cpus", "2",
                "--memory", "4g",
                "simforge-elmer:latest",
                "ElmerSolver", "case.sif"
            ]
            
            start_time = time.time()
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=600)
            elapsed = time.time() - start_time
            
            if result.returncode != 0:
                print(f"[Elmer] Solver failed: {result.stderr}")
                raise Exception(f"Elmer solver failed: {result.stderr}")
                
        else:
            # Fallback: return synthetic result
            print("[Elmer] No solver available, returning synthetic result")
            return generate_synthetic_result(task_id, input_file, options)
    
    except subprocess.TimeoutExpired:
        raise Exception("Elmer solver timed out after 600 seconds")
    
    # Step 3: Parse output
    ep_path = work_dir / "case.ep"
    
    if ep_path.exists():
        from parsers.elmer_parser import parse_elmer
        parsed = parse_elmer(str(ep_path))
    else:
        # Fallback to synthetic result
        return generate_synthetic_result(task_id, input_file, options)
    
    # Step 4: Format result
    system_type = input_file.get("metadata", {}).get("system_type", "Thermal-Structural")
    return {
        "domain": "Thermal",
        "system_type": system_type,
        "solver_name": "Elmer",
        "solver_version": "9.0",
        "metrics": parsed.get("metrics", []),
        "contour_field": parsed.get("contour_field", {}),
        "visualization_type": "contour_field",
        "plain_summary": f"Multi-physics analysis complete. Max temperature: {parsed.get('metrics', [{}])[0].get('value', 0):.1f} °C",
        "raw_files": {
            "ep": str(ep_path) if ep_path.exists() else None,
            "sif": str(sif_path) if sif_path.exists() else None
        }
    }

def generate_elmer_sif(sif_path: Path, power: float, width: float, height: float,
                       thermal_cond: float, youngs_mod: float, thermal_exp: float):
    """Generate Elmer .sif file"""
    
    sif_content = f"""Header
  Mesh DB "." "."
  Include Path ""
  Results
  Results Directory ""
End

Simulation
  Model = "Heat Transfer"
  Coordinate System = Cartesian 2D
  Coordinate Mapping(3) = 1 2
  Simulation Type = Steady State
  
  Max Output Level = 5
  Output File = "case.dat"
  Post File = "case.ep"
  
  Steady State Max Iterations = 50
  Steady State Min Iterations = 2
  Linear System Solver = Iterative
  Linear System Iterative Method = BiCGStab
  Linear System Max Iterations = 500
  Linear System Convergence Tolerance = 1.0e-6
  Linear System Abort Not Converged = False
  Linear System Residual Output = 10
  Linear System Preconditioning = ILU0
  Bicgstab preconditioning = Diagonal
End

Constants
  Stefan Boltzmann = 5.670374419e-8
End

Body 1
  Target Bodies(1) = 1
  Name = "Heat Source"
  Equation = 1
  Material = 1
  Initial Condition = 1
End

Initial Condition 1
  Temperature = 293.15
End

Material 1
  Name = "Aluminum"
  Heat Conductivity = {thermal_cond}
  Heat Capacity = 896
  Density = 2700
End

Equation 1
  Active Solvers(1) = 1
  Convection = Logical True
End

Solver 1
  Equation = Heat Equation
  Variable = Temperature
  Procedure = "HeatSolve"
  
  Linear System Solver = Iterative
  Linear System Iterative Method = BiCGStab
  Linear System Max Iterations = 500
  Linear System Convergence Tolerance = 1.0e-6
  Linear System Preconditioning = ILU0
  Linear System Residual Output = 10
End

Boundary Condition 1
  Target Boundaries(1) = 1
  Name = "Heat Source"
  Heat Flux = {power / (width * height / 1e6)}
End

Boundary Condition 2
  Target Boundaries(1) = 2
  Name = "Convective"
  Heat Transfer Coefficient = 10
  External Temperature = 293.15
End
"""
    
    with open(sif_path, 'w') as f:
        f.write(sif_content)

def generate_synthetic_result(task_id: str, input_file: Dict[str, Any], options: Dict[str, Any]) -> Dict[str, Any]:
    """Generate synthetic multi-physics result (fallback when solver unavailable)
    
    Note: Uses placeholder defaults since model parameters are not available in this fallback path.
    """
    # Placeholder defaults for synthetic result
    power = 25.0  # W, default fallback
    width = 50.0  # mm, default fallback
    height = 50.0  # mm, default fallback
    thermal_cond = 200.0  # W/(m·K), aluminum default
    youngs_mod = 69.0  # GPa, aluminum default
    thermal_exp = 23e-6  # 1/K, aluminum default
    
    # Simple thermal conduction
    area = (width * height) / 1e6  # m²
    max_temp = 293.15 + power / (thermal_cond * area) * 0.01  # Approximate
    
    # Thermal stress
    delta_T = max_temp - 293.15
    thermal_stress = youngs_mod * 1e9 * thermal_exp * delta_T / 1e6  # MPa
    
    # Generate synthetic contour field
    n_points = 100
    x = [i * width / (n_points - 1) for i in range(n_points)]
    y = [0] * n_points
    z = [0] * n_points
    temperature = [max_temp - (max_temp - 293.15) * (xi / width) for xi in x]
    stress = [thermal_stress * (1 - xi / width) for xi in x]
    
    return {
        "domain": "Thermal",
        "system_type": "Thermal-Structural",
        "solver_name": "Elmer",
        "solver_version": "9.0",
        "metrics": [
            {"name": "Max Temperature", "value": f"{max_temp:.1f}", "unit": "K"},
            {"name": "Thermal Stress", "value": f"{thermal_stress:.1f}", "unit": "MPa"},
            {"name": "Note", "value": "Synthetic result - solver unavailable", "unit": ""}
        ],
        "contour_field": {
            "x": x,
            "y": y,
            "z": z,
            "temperature": temperature,
            "stress": stress
        },
        "visualization_type": "contour_field",
        "plain_summary": f"Synthetic multi-physics result (solver unavailable). Max temp: {max_temp:.1f} K"
    }
