"""
ngspice Solver
Circuit simulation solver running in Docker container
"""

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from typing import Dict, Any
import subprocess
import shutil
from pathlib import Path
import time
import math

def run_ngspice_docker(task_id: str, input_file: Dict[str, Any], options: Dict[str, Any]) -> Dict[str, Any]:
    """
    Run ngspice solver in Docker container
    
    Args:
        task_id: Task UUID
        input_file: {filename, content} - complete ngspice netlist
        options: Additional options
    """
    
    # Extract netlist content from input_file
    netlist_content = input_file.get("content", "")
    filename = input_file.get("filename", "circuit.cir")
    
    # Create working directory (use project directory for better Docker volume support on macOS)
    base_dir = Path(__file__).parent.parent.parent / "simforge_runs"
    base_dir.mkdir(parents=True, exist_ok=True)
    work_dir = base_dir / task_id
    work_dir.mkdir(parents=True, exist_ok=True)
    
    # Step 1: Write netlist to file (already generated by AI)
    netlist_path = work_dir / filename
    
    with open(netlist_path, 'w') as f:
        f.write(netlist_content)
    
    # Step 2: Run Docker container
    print(f"[ngspice] Running solver for task {task_id}")
    
    try:
        # Check if ngspice is available directly on host
        ngspice_available = shutil.which("ngspice") is not None
        
        if ngspice_available:
            # Run ngspice directly on host
            cmd = [
                "ngspice", "-b", "-o", "ngspice.log", str(netlist_path)
            ]
            
            print(f"[ngspice] Running command: {' '.join(cmd)}")
            print(f"[ngspice] Work directory: {work_dir}")
            print(f"[ngspice] Netlist exists: {netlist_path.exists()}")
            
            start_time = time.time()
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=120, cwd=work_dir)
            elapsed = time.time() - start_time
            
            print(f"[ngspice] Return code: {result.returncode}")
            print(f"[ngspice] Stdout: {result.stdout}")
            print(f"[ngspice] Stderr: {result.stderr}")
            
            # Check for output files even if return code is non-zero
            # ngspice sometimes returns non-zero for warnings but still produces output
            # Look for any .raw file in the work directory
            raw_files = list(work_dir.glob("*.raw"))
            raw_path = raw_files[0] if raw_files else work_dir / "circuit.raw"
            log_path = work_dir / "ngspice.log"
            
            print(f"[ngspice] Raw file exists: {raw_path.exists()}")
            print(f"[ngspice] Log file exists: {log_path.exists()}")
            
            if log_path.exists():
                with open(log_path, 'r') as f:
                    print(f"[ngspice] Log content: {f.read()[:500]}")
            
            # Only fail if no output files were generated
            if result.returncode != 0 and not raw_path.exists():
                print(f"[ngspice] Solver failed and no output file generated")
                raise Exception(f"ngspice solver failed: {result.stderr}")
        elif shutil.which("docker") is not None:
            # Run in Docker
            cmd = [
                "docker", "run", "--rm",
                "-v", f"{work_dir}:/work",
                "-w", "/work",
                "simforge-ngspice:latest",
                "ngspice", "-b", "-o", "ngspice.log", filename
            ]
            
            print(f"[ngspice] Running command: {' '.join(cmd)}")
            print(f"[ngspice] Work directory: {work_dir}")
            print(f"[ngspice] Netlist exists: {netlist_path.exists()}")
            
            start_time = time.time()
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
            elapsed = time.time() - start_time
            
            print(f"[ngspice] Return code: {result.returncode}")
            print(f"[ngspice] Stdout: {result.stdout}")
            print(f"[ngspice] Stderr: {result.stderr}")
            
            # Check for output files even if return code is non-zero
            # ngspice sometimes returns non-zero for warnings but still produces output
            # Look for any .raw file in the work directory
            raw_files = list(work_dir.glob("*.raw"))
            raw_path = raw_files[0] if raw_files else work_dir / "circuit.raw"
            log_path = work_dir / "ngspice.log"
            
            print(f"[ngspice] Raw file exists: {raw_path.exists()}")
            print(f"[ngspice] Log file exists: {log_path.exists()}")
            
            if log_path.exists():
                with open(log_path, 'r') as f:
                    print(f"[ngspice] Log content: {f.read()[:500]}")
            
            # Only fail if no output files were generated
            if result.returncode != 0 and not raw_path.exists():
                print(f"[ngspice] Solver failed and no output file generated")
                raise Exception(f"ngspice solver failed: {result.stderr}")
        else:
            # No ngspice or Docker available
            print("[ngspice] Neither ngspice nor Docker available")
            raise Exception("ngspice or Docker is required for ngspice solver")
    
    except subprocess.TimeoutExpired:
        raise Exception("ngspice solver timed out after 120 seconds")
    except Exception as e:
        raise Exception(f"ngspice solver error: {e}")
    
    # Step 3: Parse output
    raw_files = list(work_dir.glob("*.raw"))
    raw_path = raw_files[0] if raw_files else work_dir / "circuit.raw"

    if raw_path.exists():
        from parsers.ngspice_parser import parse_raw
        parsed = parse_raw(str(raw_path))
    else:
        raise Exception("ngspice solver did not generate output file")
    
    # Step 4: Format result
    # Find a voltage metric for the summary (skip frequency range or other non-voltage metrics)
    metrics = parsed.get("metrics", [])
    voltage_value = 0.0
    for metric in metrics:
        metric_name = metric.get("name", "").lower()
        if "voltage" in metric_name or "v(" in metric_name:
            try:
                voltage_value = float(metric.get("value", 0))
                break
            except ValueError:
                continue
    
    return {
        "domain": "Circuits",
        "system_type": "RC Low-Pass Filter",  # Default, could be parsed from netlist
        "solver_name": "ngspice",
        "solver_version": "42",
        "metrics": metrics,
        "time_series": parsed.get("time_series", {}),
        "frequency_response": parsed.get("frequency_response", {}),
        "visualization_type": parsed.get("visualization_type", "time_series"),
        "plain_summary": f"Circuit simulation complete. Output voltage: {voltage_value:.2f} V",
        "raw_files": {
            "netlist": str(netlist_path) if 'netlist_path' in locals() and netlist_path.exists() else None,
            "output": str(raw_path) if 'raw_path' in locals() and raw_path.exists() else None
        }
    }

def generate_netlist(netlist_path: Path, system_type: str, components: Dict[str, Any],
                     input_params: Dict[str, Any], simulation: Dict[str, Any]):
    """Generate ngspice netlist from model"""
    
    # Extract component values
    vin = input_params.get("Supply voltage", {}).get("value", 12)
    r1 = components.get("Resistor (R1)", {}).get("value", "1k")
    r2 = components.get("Resistor (R2)", {}).get("value", "1k")
    c1 = components.get("Capacitor (C1)", {}).get("value", "1u")
    
    # Parse units (simplified)
    def parse_value(val):
        if isinstance(val, (int, float)):
            return float(val)
        val_str = str(val).lower()
        
        # Remove unit suffixes
        units = ['v', 'a', 'ohm', 'ω', 'f', 'h', 'w', 'hz', 's']
        for unit in units:
            val_str = val_str.replace(unit, '')
        
        val_str = val_str.strip()
        
        if 'k' in val_str:
            return float(val_str.replace('k', '')) * 1e3
        elif 'm' in val_str:
            return float(val_str.replace('m', '')) * 1e-3
        elif 'u' in val_str or 'µ' in val_str:
            val_str = val_str.replace('µ', '').replace('u', '')
            return float(val_str) * 1e-6
        elif 'n' in val_str:
            return float(val_str.replace('n', '')) * 1e-9
        elif 'p' in val_str:
            return float(val_str.replace('p', '')) * 1e-12
        else:
            return float(val_str)
    
    r1_val = parse_value(r1)
    r2_val = parse_value(r2)
    c1_val = parse_value(c1)
    vin_val = parse_value(vin)
    
    # Generate netlist based on system type
    if "rc" in system_type and "filter" in system_type:
        # RC low-pass filter
        netlist = f"""* RC Low-Pass Filter
* Generated by SimForge

Vin 1 0 DC {vin_val} AC 1
R1 1 2 {r1_val}
C1 2 0 {c1_val}

.AC DEC 10 10 100k
.TRAN 1u 10m

.PLOT AC V(2)
.PLOT TRAN V(2)
.END
"""
    else:
        # Generic voltage divider - use transient to get .raw output
        netlist = f"""* Voltage Divider
* Generated by SimForge

Vin 1 0 DC {vin_val}
R1 1 2 {r1_val}
R2 2 0 {r2_val}

.TRAN 1u 10m
.control
set filetype=ascii
run
write circuit.raw
quit
.endc
.END
"""
    
    with open(netlist_path, 'w') as f:
        f.write(netlist)

def generate_synthetic_result(system_type: str, components: Dict[str, Any],
                            input_params: Dict[str, Any], simulation: Dict[str, Any]) -> Dict[str, Any]:
    """Generate synthetic circuit result (fallback when solver unavailable)"""
    
    # Extract values
    vin = input_params.get("Supply voltage", {}).get("value", 12)
    r1 = components.get("Resistor (R1)", {}).get("value", "1k")
    r2 = components.get("Resistor (R2)", {}).get("value", "1k")
    c1 = components.get("Capacitor (C1)", {}).get("value", "1u")
    
    # Parse values
    def parse_value(val):
        if isinstance(val, (int, float)):
            return float(val)
        val_str = str(val).lower()
        if 'k' in val_str:
            return float(val_str.replace('k', '')) * 1e3
        elif 'm' in val_str:
            return float(val_str.replace('m', '')) * 1e-3
        elif 'u' in val_str:
            return float(val_str.replace('u', '')) * 1e-6
        else:
            return float(val_str)
    
    r1_val = parse_value(r1)
    r2_val = parse_value(r2)
    c1_val = parse_value(c1)
    vin_val = parse_value(vin)
    
    if "rc" in system_type and "filter" in system_type:
        # RC filter frequency response
        fc = 1 / (2 * math.pi * r1_val * c1_val)
        
        freqs = []
        mags = []
        phases = []
        
        f_min = 10
        f_max = 100000
        for i in range(100):
            f = f_min * (f_max / f_min) ** (i / 99)
            freqs.append(f)
            w = 2 * math.pi * f
            wrc = w * r1_val * c1_val
            mag = 20 * math.log10(1 / math.sqrt(1 + wrc**2))
            phase = -math.atan(wrc) * 180 / math.pi
            mags.append(mag)
            phases.append(phase)
        
        return {
            "domain": "Circuits",
            "system_type": "RC Low-Pass Filter",
            "solver_name": "ngspice",
            "solver_version": "42",
            "metrics": [
                {"name": "Cutoff Frequency", "value": f"{fc:.1f}", "unit": "Hz"},
                {"name": "Note", "value": "Synthetic result - solver unavailable", "unit": ""}
            ],
            "frequency_response": {
                "freq": freqs,
                "mag": mags,
                "phase": phases
            },
            "visualization_type": "frequency_response",
            "plain_summary": f"Synthetic RC filter result (solver unavailable). Cutoff: {fc:.1f} Hz"
        }
    else:
        # Voltage divider
        vout = vin_val * r2_val / (r1_val + r2_val)
        
        return {
            "domain": "Circuits",
            "system_type": "Voltage Divider",
            "solver_name": "ngspice",
            "solver_version": "42",
            "metrics": [
                {"name": "Output Voltage", "value": f"{vout:.2f}", "unit": "V"},
                {"name": "Note", "value": "Synthetic result - solver unavailable", "unit": ""}
            ],
            "visualization_type": "none",
            "plain_summary": f"Synthetic voltage divider result (solver unavailable). Vout: {vout:.2f} V"
        }
