"""
XFOIL Solver
2D airfoil analysis solver running in Docker container
"""

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from typing import Dict, Any
import subprocess
import shutil
from pathlib import Path
import time

def run_xfoil_docker(task_id: str, input_file: Dict[str, Any], options: Dict[str, Any]) -> Dict[str, Any]:
    """
    Run XFOIL solver in Docker container
    
    Args:
        task_id: Task UUID
        input_file: {filename, content} - complete XFOIL input script
        options: Additional options
    """
    
    # Extract input script content from input_file
    script_content = input_file.get("content", "")
    filename = input_file.get("filename", "xfoil_input.txt")
    
    # Create working directory (use project directory for better Docker volume support on macOS)
    base_dir = Path(__file__).parent.parent.parent / "simforge_runs"
    base_dir.mkdir(parents=True, exist_ok=True)
    work_dir = base_dir / task_id
    work_dir.mkdir(parents=True, exist_ok=True)
    
    # Step 1: Write input script to file (already generated by AI)
    input_script = work_dir / filename
    
    with open(input_script, 'w') as f:
        f.write(script_content)
    
    # Step 2: Run Docker container
    print(f"[XFOIL] Running solver for task {task_id}")
    
    try:
        # Check if Docker is available
        docker_available = shutil.which("docker") is not None
        
        if docker_available:
            # Run in Docker with stdin piped via Python
            # Input file already written in Step 1 (AI-generated)
            
            cmd = [
                "docker", "run", "--rm",
                "-i",  # Keep stdin open
                "-v", f"{work_dir}:/work",
                "-w", "/work",
                "simforge-xfoil:latest",
                "xfoil"
            ]
            
            # Read input file and pipe via stdin
            with open(input_script, 'r') as f:
                xfoil_stdin = f.read()
            
            start_time = time.time()
            result = subprocess.run(cmd, input=xfoil_stdin, capture_output=True, text=True, timeout=120)
            elapsed = time.time() - start_time
            
            if result.returncode != 0:
                print(f"[XFOIL] Solver failed: {result.stderr}")
                raise Exception(f"XFOIL solver failed: {result.stderr}")
                
        else:
            # Fallback: return synthetic result
            print("[XFOIL] No solver available, returning synthetic result")
            return generate_synthetic_result(task_id, input_file, options)
    
    except subprocess.TimeoutExpired:
        raise Exception("XFOIL solver timed out after 120 seconds")
    
    # Step 3: Parse output
    polar_path = work_dir / "polar.txt"
    
    if polar_path.exists():
        from parsers.xfoil_parser import parse_polar
        parsed = parse_polar(str(polar_path))
    else:
        # Fallback to synthetic result
        return generate_synthetic_result(task_id, input_file, options)
    
    # Step 4: Format result
    system_type = input_file.get("metadata", {}).get("system_type", "Airfoil Analysis")
    return {
        "domain": "Aerospace",
        "system_type": system_type,
        "solver_name": "XFOIL",
        "solver_version": "6.99",
        "metrics": parsed.get("metrics", []),
        "frequency_response": parsed.get("frequency_response", {}),
        "visualization_type": "frequency_response",
        "plain_summary": f"Airfoil analysis complete. Max CL: {float(parsed.get('metrics', [{}])[0].get('value', 0)):.2f}",
        "raw_files": {
            "output": str(polar_path) if polar_path.exists() else None
        }
    }

def generate_xfoil_input(input_path: Path, airfoil: str, reynolds: float, mach: float,
                         aoa_min: float, aoa_max: float, aoa_step: float, ncrit: int):
    """Generate XFOIL input script"""
    
    input_content = f"""LOAD
{airfoil}
PANE
OPER
VISC {reynolds}
MACH {mach}
VPAR
N {ncrit}

PACC
polar.txt

ASEQ {aoa_min} {aoa_max} {aoa_step}
PACC
QUIT
"""
    
    with open(input_path, 'w') as f:
        f.write(input_content)

def generate_synthetic_result(task_id: str, input_file: Dict[str, Any], options: Dict[str, Any]) -> Dict[str, Any]:
    """Generate synthetic airfoil polar (fallback when solver unavailable)
    
    Note: Uses placeholder defaults since model parameters are not available in this fallback path.
    """
    # Placeholder defaults for synthetic result
    airfoil = "naca0012"
    reynolds = 1e6
    mach = 0.0
    aoa_min = -5.0
    aoa_max = 15.0
    aoa_step = 1.0
    ncrit = 9
    
    # Generate synthetic polar data using simplified airfoil theory
    aoa_values = []
    cl_values = []
    cd_values = []
    
    for aoa in range(int(aoa_min), int(aoa_max) + 1, int(aoa_step)):
        aoa_rad = aoa * 3.14159 / 180
        
        # Simplified lift coefficient (linear region)
        if aoa < 12:
            cl = 0.1 + 0.1 * aoa
        else:
            # Stall
            cl = 1.3 - 0.05 * (aoa - 12)
        
        # Simplified drag coefficient
        cd = 0.01 + 0.01 * (cl ** 2)
        
        aoa_values.append(aoa)
        cl_values.append(max(0, cl))
        cd_values.append(max(0.01, cd))
    
    # Find max CL and stall angle
    max_cl = max(cl_values)
    stall_angle = aoa_values[cl_values.index(max_cl)]
    
    # Calculate L/D ratio
    ld_ratios = [cl / cd if cd > 0 else 0 for cl, cd in zip(cl_values, cd_values)]
    max_ld = max(ld_ratios)
    
    return {
        "domain": "Aerospace",
        "system_type": "Airfoil Analysis",
        "solver_name": "XFOIL",
        "solver_version": "6.99",
        "metrics": [
            {"name": "Max CL", "value": max_cl, "unit": ""},
            {"name": "Stall Angle", "value": float(stall_angle), "unit": "deg"},
            {"name": "Max L/D", "value": max_ld, "unit": ""},
            {"name": "Note", "value": "Synthetic result - solver unavailable", "unit": ""}
        ],
        "frequency_response": {
            "freq": aoa_values,  # Using AoA as "frequency"
            "mag": cl_values,    # Using CL as "magnitude"
            "phase": cd_values   # Using CD as secondary
        },
        "visualization_type": "frequency_response",
        "plain_summary": f"Synthetic airfoil polar (solver unavailable). Max CL: {max_cl:.2f} at {stall_angle}°"
    }
